# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from chat_service.chat.grpc import chat_pb2 as chat__service_dot_chat_dot_grpc_dot_chat__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in chat_service/chat/grpc/chat_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatRoomControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/chat_service.chat.ChatRoomController/Create',
                request_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomRequest.SerializeToString,
                response_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomResponse.FromString,
                _registered_method=True)
        self.Destroy = channel.unary_unary(
                '/chat_service.chat.ChatRoomController/Destroy',
                request_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/chat_service.chat.ChatRoomController/List',
                request_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomListRequest.SerializeToString,
                response_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomListResponse.FromString,
                _registered_method=True)
        self.ListChatRooms = channel.unary_unary(
                '/chat_service.chat.ChatRoomController/ListChatRooms',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomResponse.FromString,
                _registered_method=True)
        self.PartialUpdate = channel.unary_unary(
                '/chat_service.chat.ChatRoomController/PartialUpdate',
                request_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomPartialUpdateRequest.SerializeToString,
                response_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/chat_service.chat.ChatRoomController/Retrieve',
                request_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomRetrieveRequest.SerializeToString,
                response_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/chat_service.chat.ChatRoomController/Update',
                request_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomRequest.SerializeToString,
                response_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomResponse.FromString,
                _registered_method=True)


class ChatRoomControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChatRooms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatRoomControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomRequest.FromString,
                    response_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomListRequest.FromString,
                    response_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomListResponse.SerializeToString,
            ),
            'ListChatRooms': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChatRooms,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomPartialUpdateRequest.FromString,
                    response_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomRetrieveRequest.FromString,
                    response_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomRequest.FromString,
                    response_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat_service.chat.ChatRoomController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chat_service.chat.ChatRoomController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatRoomController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat_service.chat.ChatRoomController/Create',
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomRequest.SerializeToString,
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat_service.chat.ChatRoomController/Destroy',
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat_service.chat.ChatRoomController/List',
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomListRequest.SerializeToString,
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChatRooms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat_service.chat.ChatRoomController/ListChatRooms',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat_service.chat.ChatRoomController/PartialUpdate',
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomPartialUpdateRequest.SerializeToString,
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat_service.chat.ChatRoomController/Retrieve',
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomRetrieveRequest.SerializeToString,
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat_service.chat.ChatRoomController/Update',
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomRequest.SerializeToString,
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ChatRoomMessageControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/chat_service.chat.ChatRoomMessageController/Create',
                request_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageRequest.SerializeToString,
                response_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageResponse.FromString,
                _registered_method=True)
        self.Destroy = channel.unary_unary(
                '/chat_service.chat.ChatRoomMessageController/Destroy',
                request_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/chat_service.chat.ChatRoomMessageController/List',
                request_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageListRequest.SerializeToString,
                response_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageListResponse.FromString,
                _registered_method=True)
        self.PartialUpdate = channel.unary_unary(
                '/chat_service.chat.ChatRoomMessageController/PartialUpdate',
                request_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessagePartialUpdateRequest.SerializeToString,
                response_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/chat_service.chat.ChatRoomMessageController/Retrieve',
                request_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageRetrieveRequest.SerializeToString,
                response_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageResponse.FromString,
                _registered_method=True)
        self.SubscribeChatRoomMessages = channel.unary_stream(
                '/chat_service.chat.ChatRoomMessageController/SubscribeChatRoomMessages',
                request_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageSubscribeChatRoomMessagesRequest.SerializeToString,
                response_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/chat_service.chat.ChatRoomMessageController/Update',
                request_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageRequest.SerializeToString,
                response_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageResponse.FromString,
                _registered_method=True)


class ChatRoomMessageControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeChatRoomMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatRoomMessageControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageRequest.FromString,
                    response_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageListRequest.FromString,
                    response_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageListResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessagePartialUpdateRequest.FromString,
                    response_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageRetrieveRequest.FromString,
                    response_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageResponse.SerializeToString,
            ),
            'SubscribeChatRoomMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeChatRoomMessages,
                    request_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageSubscribeChatRoomMessagesRequest.FromString,
                    response_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageRequest.FromString,
                    response_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat_service.chat.ChatRoomMessageController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chat_service.chat.ChatRoomMessageController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatRoomMessageController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat_service.chat.ChatRoomMessageController/Create',
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageRequest.SerializeToString,
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat_service.chat.ChatRoomMessageController/Destroy',
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat_service.chat.ChatRoomMessageController/List',
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageListRequest.SerializeToString,
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat_service.chat.ChatRoomMessageController/PartialUpdate',
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessagePartialUpdateRequest.SerializeToString,
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat_service.chat.ChatRoomMessageController/Retrieve',
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageRetrieveRequest.SerializeToString,
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeChatRoomMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/chat_service.chat.ChatRoomMessageController/SubscribeChatRoomMessages',
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageSubscribeChatRoomMessagesRequest.SerializeToString,
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat_service.chat.ChatRoomMessageController/Update',
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageRequest.SerializeToString,
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ChatRoomUserControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/chat_service.chat.ChatRoomUserController/Create',
                request_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserRequest.SerializeToString,
                response_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserResponse.FromString,
                _registered_method=True)
        self.Destroy = channel.unary_unary(
                '/chat_service.chat.ChatRoomUserController/Destroy',
                request_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetChatRoomByUserId = channel.unary_stream(
                '/chat_service.chat.ChatRoomUserController/GetChatRoomByUserId',
                request_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserGetChatRoomByUserIdRequest.SerializeToString,
                response_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/chat_service.chat.ChatRoomUserController/List',
                request_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserListRequest.SerializeToString,
                response_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserListResponse.FromString,
                _registered_method=True)
        self.PartialUpdate = channel.unary_unary(
                '/chat_service.chat.ChatRoomUserController/PartialUpdate',
                request_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserPartialUpdateRequest.SerializeToString,
                response_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/chat_service.chat.ChatRoomUserController/Retrieve',
                request_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserRetrieveRequest.SerializeToString,
                response_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/chat_service.chat.ChatRoomUserController/Update',
                request_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserRequest.SerializeToString,
                response_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserResponse.FromString,
                _registered_method=True)


class ChatRoomUserControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChatRoomByUserId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatRoomUserControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserRequest.FromString,
                    response_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetChatRoomByUserId': grpc.unary_stream_rpc_method_handler(
                    servicer.GetChatRoomByUserId,
                    request_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserGetChatRoomByUserIdRequest.FromString,
                    response_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserListRequest.FromString,
                    response_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserListResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserPartialUpdateRequest.FromString,
                    response_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserRetrieveRequest.FromString,
                    response_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserRequest.FromString,
                    response_serializer=chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat_service.chat.ChatRoomUserController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chat_service.chat.ChatRoomUserController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatRoomUserController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat_service.chat.ChatRoomUserController/Create',
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserRequest.SerializeToString,
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat_service.chat.ChatRoomUserController/Destroy',
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChatRoomByUserId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/chat_service.chat.ChatRoomUserController/GetChatRoomByUserId',
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserGetChatRoomByUserIdRequest.SerializeToString,
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat_service.chat.ChatRoomUserController/List',
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserListRequest.SerializeToString,
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat_service.chat.ChatRoomUserController/PartialUpdate',
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserPartialUpdateRequest.SerializeToString,
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat_service.chat.ChatRoomUserController/Retrieve',
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserRetrieveRequest.SerializeToString,
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat_service.chat.ChatRoomUserController/Update',
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserRequest.SerializeToString,
            chat__service_dot_chat_dot_grpc_dot_chat__pb2.ChatRoomUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
