# Generated by Django 3.2.16 on 2025-01-03 21:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='stat',
            name='game_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='loser_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='winner_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserStat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.PositiveIntegerField()),
                ('did_win', models.BooleanField(default=False)),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='stats.stat')),
            ],
        ),
    ]
