# Generated by Django 3.2.16 on 2025-01-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20241229_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='game_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
