# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\x12\x04game\"\x12\n\x04Game\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1c\n\x0eGetGameRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1f\n\x11\x43reateGameRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"%\n\x08GameList\x12\x19\n\x05games\x18\x01 \x03(\x0b\x32\n.game.Game\"\x07\n\x05\x45mpty2\x96\x01\n\x0bGameService\x12+\n\x07GetGame\x12\x14.game.GetGameRequest\x1a\n.game.Game\x12\x31\n\nCreateGame\x12\x17.game.CreateGameRequest\x1a\n.game.Game\x12\'\n\x08GetGames\x12\x0b.game.Empty\x1a\x0e.game.GameListb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GAME._serialized_start=20
  _GAME._serialized_end=38
  _GETGAMEREQUEST._serialized_start=40
  _GETGAMEREQUEST._serialized_end=68
  _CREATEGAMEREQUEST._serialized_start=70
  _CREATEGAMEREQUEST._serialized_end=101
  _GAMELIST._serialized_start=103
  _GAMELIST._serialized_end=140
  _EMPTY._serialized_start=142
  _EMPTY._serialized_end=149
  _GAMESERVICE._serialized_start=152
  _GAMESERVICE._serialized_end=302
# @@protoc_insertion_point(module_scope)
