# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\x12\rtranscendence\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xef\x01\n\x04Game\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05state\x18\x02 \x01(\t\x12\x17\n\x0fpoints_player_a\x18\x03 \x01(\x05\x12\x17\n\x0fpoints_player_b\x18\x04 \x01(\x05\x12\x13\n\x0bplayer_a_id\x18\x05 \x01(\x05\x12\x13\n\x0bplayer_b_id\x18\x06 \x01(\x05\x12\x10\n\x08\x66inished\x18\x07 \x01(\x08\x12.\n\ncreated_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"!\n\x0eGetGameRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\x05\"\x18\n\x16GetOngoingGamesRequest\"=\n\x17GetOngoingGamesResponse\x12\"\n\x05games\x18\x01 \x03(\x0b\x32\x13.transcendence.Game\"~\n\x11\x43reateGameRequest\x12\r\n\x05state\x18\x01 \x01(\t\x12\x17\n\x0fpoints_player_a\x18\x02 \x01(\x05\x12\x17\n\x0fpoints_player_b\x18\x03 \x01(\x05\x12\x13\n\x0bplayer_a_id\x18\x04 \x01(\x05\x12\x13\n\x0bplayer_b_id\x18\x05 \x01(\x05\"#\n\x10StartGameRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\x05\";\n\x11StartGameResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rwebsocket_url\x18\x02 \x01(\t\"r\n\x13GameFinishedRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\x05\x12\x17\n\x0fpoints_player_a\x18\x02 \x01(\x05\x12\x17\n\x0fpoints_player_b\x18\x03 \x01(\x05\x12\x18\n\x10winner_player_id\x18\x04 \x01(\x05\x32\x95\x03\n\x0bGameService\x12=\n\x07GetGame\x12\x1d.transcendence.GetGameRequest\x1a\x13.transcendence.Game\x12`\n\x0fGetOngoingGames\x12%.transcendence.GetOngoingGamesRequest\x1a&.transcendence.GetOngoingGamesResponse\x12\x43\n\nCreateGame\x12 .transcendence.CreateGameRequest\x1a\x13.transcendence.Game\x12N\n\tStartGame\x12\x1f.transcendence.StartGameRequest\x1a .transcendence.StartGameResponse\x12P\n\x12HandleGameFinished\x12\".transcendence.GameFinishedRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GAME._serialized_start=92
  _GAME._serialized_end=331
  _GETGAMEREQUEST._serialized_start=333
  _GETGAMEREQUEST._serialized_end=366
  _GETONGOINGGAMESREQUEST._serialized_start=368
  _GETONGOINGGAMESREQUEST._serialized_end=392
  _GETONGOINGGAMESRESPONSE._serialized_start=394
  _GETONGOINGGAMESRESPONSE._serialized_end=455
  _CREATEGAMEREQUEST._serialized_start=457
  _CREATEGAMEREQUEST._serialized_end=583
  _STARTGAMEREQUEST._serialized_start=585
  _STARTGAMEREQUEST._serialized_end=620
  _STARTGAMERESPONSE._serialized_start=622
  _STARTGAMERESPONSE._serialized_end=681
  _GAMEFINISHEDREQUEST._serialized_start=683
  _GAMEFINISHEDREQUEST._serialized_end=797
  _GAMESERVICE._serialized_start=800
  _GAMESERVICE._serialized_end=1205
# @@protoc_insertion_point(module_scope)
