# Generated by Django 3.2.16 on 2025-01-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20241231_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player_b_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
