# Generated by Django 4.2.17 on 2025-01-18 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_player_b_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('play_order', models.IntegerField()),
                ('games_played', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='game.tournamentroom')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentGameMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_mappings', to='game.game')),
                ('tournament_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='game.tournamentroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_game_mappings', to='game.tournamentuser')),
            ],
        ),
    ]
