# Generated by Django 4.2.17 on 2025-01-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_tournamentroom_tournamentuser_tournamentgamemapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='tournamentuser',
            constraint=models.UniqueConstraint(fields=('user_id', 'tournament_room'), name='unique_user_tournament'),
        ),
    ]
