# Generated by Django 4.2.17 on 2025-01-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_tournamentroom_start_time_tournamentroom_started_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentroom',
            name='chat_room_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
