# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import auth_pb2 as auth__pb2


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRedirectUri = channel.unary_unary(
                '/auth.AuthService/GetRedirectUri',
                request_serializer=auth__pb2.Empty.SerializeToString,
                response_deserializer=auth__pb2.RedirectUriResponse.FromString,
                )
        self.ExchangeCodeForToken = channel.unary_unary(
                '/auth.AuthService/ExchangeCodeForToken',
                request_serializer=auth__pb2.ExchangeCodeRequest.SerializeToString,
                response_deserializer=auth__pb2.ExchangeCodeResponse.FromString,
                )
        self.GetUserIDFromJwtToken = channel.unary_unary(
                '/auth.AuthService/GetUserIDFromJwtToken',
                request_serializer=auth__pb2.GetUserIDFromJwtTokenRequest.SerializeToString,
                response_deserializer=auth__pb2.GetUserIDFromJwtTokenResponse.FromString,
                )


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRedirectUri(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExchangeCodeForToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserIDFromJwtToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRedirectUri': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRedirectUri,
                    request_deserializer=auth__pb2.Empty.FromString,
                    response_serializer=auth__pb2.RedirectUriResponse.SerializeToString,
            ),
            'ExchangeCodeForToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ExchangeCodeForToken,
                    request_deserializer=auth__pb2.ExchangeCodeRequest.FromString,
                    response_serializer=auth__pb2.ExchangeCodeResponse.SerializeToString,
            ),
            'GetUserIDFromJwtToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserIDFromJwtToken,
                    request_deserializer=auth__pb2.GetUserIDFromJwtTokenRequest.FromString,
                    response_serializer=auth__pb2.GetUserIDFromJwtTokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRedirectUri(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.AuthService/GetRedirectUri',
            auth__pb2.Empty.SerializeToString,
            auth__pb2.RedirectUriResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExchangeCodeForToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.AuthService/ExchangeCodeForToken',
            auth__pb2.ExchangeCodeRequest.SerializeToString,
            auth__pb2.ExchangeCodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserIDFromJwtToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.AuthService/GetUserIDFromJwtToken',
            auth__pb2.GetUserIDFromJwtTokenRequest.SerializeToString,
            auth__pb2.GetUserIDFromJwtTokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
