# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import friendship_pb2 as friendship__pb2


class FriendshipServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateFriendship = channel.unary_unary(
                '/models.FriendshipService/CreateFriendship',
                request_serializer=friendship__pb2.CreateFriendshipRequest.SerializeToString,
                response_deserializer=friendship__pb2.Friendship.FromString,
                )
        self.GetFriendshipById = channel.unary_unary(
                '/models.FriendshipService/GetFriendshipById',
                request_serializer=friendship__pb2.GetFriendshipByIdRequest.SerializeToString,
                response_deserializer=friendship__pb2.Friendship.FromString,
                )
        self.GetFriendshipsByUserId = channel.unary_unary(
                '/models.FriendshipService/GetFriendshipsByUserId',
                request_serializer=friendship__pb2.GetFriendshipsByUserIdRequest.SerializeToString,
                response_deserializer=friendship__pb2.FriendshipsResponse.FromString,
                )
        self.GetFriendshipsByFriendId = channel.unary_unary(
                '/models.FriendshipService/GetFriendshipsByFriendId',
                request_serializer=friendship__pb2.GetFriendshipsByFriendIdRequest.SerializeToString,
                response_deserializer=friendship__pb2.FriendshipsResponse.FromString,
                )


class FriendshipServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateFriendship(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFriendshipById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFriendshipsByUserId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFriendshipsByFriendId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FriendshipServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateFriendship': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFriendship,
                    request_deserializer=friendship__pb2.CreateFriendshipRequest.FromString,
                    response_serializer=friendship__pb2.Friendship.SerializeToString,
            ),
            'GetFriendshipById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFriendshipById,
                    request_deserializer=friendship__pb2.GetFriendshipByIdRequest.FromString,
                    response_serializer=friendship__pb2.Friendship.SerializeToString,
            ),
            'GetFriendshipsByUserId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFriendshipsByUserId,
                    request_deserializer=friendship__pb2.GetFriendshipsByUserIdRequest.FromString,
                    response_serializer=friendship__pb2.FriendshipsResponse.SerializeToString,
            ),
            'GetFriendshipsByFriendId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFriendshipsByFriendId,
                    request_deserializer=friendship__pb2.GetFriendshipsByFriendIdRequest.FromString,
                    response_serializer=friendship__pb2.FriendshipsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'models.FriendshipService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FriendshipService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateFriendship(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/models.FriendshipService/CreateFriendship',
            friendship__pb2.CreateFriendshipRequest.SerializeToString,
            friendship__pb2.Friendship.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFriendshipById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/models.FriendshipService/GetFriendshipById',
            friendship__pb2.GetFriendshipByIdRequest.SerializeToString,
            friendship__pb2.Friendship.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFriendshipsByUserId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/models.FriendshipService/GetFriendshipsByUserId',
            friendship__pb2.GetFriendshipsByUserIdRequest.SerializeToString,
            friendship__pb2.FriendshipsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFriendshipsByFriendId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/models.FriendshipService/GetFriendshipsByFriendId',
            friendship__pb2.GetFriendshipsByFriendIdRequest.SerializeToString,
            friendship__pb2.FriendshipsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
