# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import permission_pb2 as permission__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in permission_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PermissionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePermission = channel.unary_unary(
                '/models.PermissionService/CreatePermission',
                request_serializer=permission__pb2.CreatePermissionRequest.SerializeToString,
                response_deserializer=permission__pb2.Permission.FromString,
                _registered_method=True)
        self.GetPermissionById = channel.unary_unary(
                '/models.PermissionService/GetPermissionById',
                request_serializer=permission__pb2.GetPermissionByIdRequest.SerializeToString,
                response_deserializer=permission__pb2.Permission.FromString,
                _registered_method=True)


class PermissionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePermission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPermissionById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PermissionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePermission': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePermission,
                    request_deserializer=permission__pb2.CreatePermissionRequest.FromString,
                    response_serializer=permission__pb2.Permission.SerializeToString,
            ),
            'GetPermissionById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPermissionById,
                    request_deserializer=permission__pb2.GetPermissionByIdRequest.FromString,
                    response_serializer=permission__pb2.Permission.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'models.PermissionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('models.PermissionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PermissionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/models.PermissionService/CreatePermission',
            permission__pb2.CreatePermissionRequest.SerializeToString,
            permission__pb2.Permission.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPermissionById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/models.PermissionService/GetPermissionById',
            permission__pb2.GetPermissionByIdRequest.SerializeToString,
            permission__pb2.Permission.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
