# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: profile.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'profile.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rprofile.proto\x12\x06models\"r\n\x07Profile\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x12\n\navatar_url\x18\x03 \x01(\t\x12\x10\n\x08nickname\x18\x04 \x01(\t\x12\x0b\n\x03\x62io\x18\x05 \x01(\t\x12\x17\n\x0f\x61\x64\x64itional_info\x18\x06 \x01(\t\"s\n\x14\x43reateProfileRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x12\n\navatar_url\x18\x02 \x01(\t\x12\x10\n\x08nickname\x18\x03 \x01(\t\x12\x0b\n\x03\x62io\x18\x04 \x01(\t\x12\x17\n\x0f\x61\x64\x64itional_info\x18\x05 \x01(\t\"\x7f\n\x14UpdateProfileRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x12\n\navatar_url\x18\x03 \x01(\t\x12\x10\n\x08nickname\x18\x04 \x01(\t\x12\x0b\n\x03\x62io\x18\x05 \x01(\t\x12\x17\n\x0f\x61\x64\x64itional_info\x18\x06 \x01(\t\"#\n\x15GetProfileByIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\",\n\x19GetProfileByUserIdRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x32\x9c\x02\n\x0eProfileService\x12>\n\rCreateProfile\x12\x1c.models.CreateProfileRequest\x1a\x0f.models.Profile\x12>\n\rUpdateProfile\x12\x1c.models.UpdateProfileRequest\x1a\x0f.models.Profile\x12@\n\x0eGetProfileById\x12\x1d.models.GetProfileByIdRequest\x1a\x0f.models.Profile\x12H\n\x12GetProfileByUserId\x12!.models.GetProfileByUserIdRequest\x1a\x0f.models.Profileb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'profile_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROFILE']._serialized_start=25
  _globals['_PROFILE']._serialized_end=139
  _globals['_CREATEPROFILEREQUEST']._serialized_start=141
  _globals['_CREATEPROFILEREQUEST']._serialized_end=256
  _globals['_UPDATEPROFILEREQUEST']._serialized_start=258
  _globals['_UPDATEPROFILEREQUEST']._serialized_end=385
  _globals['_GETPROFILEBYIDREQUEST']._serialized_start=387
  _globals['_GETPROFILEBYIDREQUEST']._serialized_end=422
  _globals['_GETPROFILEBYUSERIDREQUEST']._serialized_start=424
  _globals['_GETPROFILEBYUSERIDREQUEST']._serialized_end=468
  _globals['_PROFILESERVICE']._serialized_start=471
  _globals['_PROFILESERVICE']._serialized_end=755
# @@protoc_insertion_point(module_scope)
