# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import profile_pb2 as profile__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in profile_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProfileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateProfile = channel.unary_unary(
                '/models.ProfileService/CreateProfile',
                request_serializer=profile__pb2.CreateProfileRequest.SerializeToString,
                response_deserializer=profile__pb2.Profile.FromString,
                _registered_method=True)
        self.UpdateProfile = channel.unary_unary(
                '/models.ProfileService/UpdateProfile',
                request_serializer=profile__pb2.UpdateProfileRequest.SerializeToString,
                response_deserializer=profile__pb2.Profile.FromString,
                _registered_method=True)
        self.GetProfileById = channel.unary_unary(
                '/models.ProfileService/GetProfileById',
                request_serializer=profile__pb2.GetProfileByIdRequest.SerializeToString,
                response_deserializer=profile__pb2.Profile.FromString,
                _registered_method=True)
        self.GetProfileByUserId = channel.unary_unary(
                '/models.ProfileService/GetProfileByUserId',
                request_serializer=profile__pb2.GetProfileByUserIdRequest.SerializeToString,
                response_deserializer=profile__pb2.Profile.FromString,
                _registered_method=True)


class ProfileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfileById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfileByUserId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProfile,
                    request_deserializer=profile__pb2.CreateProfileRequest.FromString,
                    response_serializer=profile__pb2.Profile.SerializeToString,
            ),
            'UpdateProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProfile,
                    request_deserializer=profile__pb2.UpdateProfileRequest.FromString,
                    response_serializer=profile__pb2.Profile.SerializeToString,
            ),
            'GetProfileById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfileById,
                    request_deserializer=profile__pb2.GetProfileByIdRequest.FromString,
                    response_serializer=profile__pb2.Profile.SerializeToString,
            ),
            'GetProfileByUserId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfileByUserId,
                    request_deserializer=profile__pb2.GetProfileByUserIdRequest.FromString,
                    response_serializer=profile__pb2.Profile.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'models.ProfileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('models.ProfileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProfileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/models.ProfileService/CreateProfile',
            profile__pb2.CreateProfileRequest.SerializeToString,
            profile__pb2.Profile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/models.ProfileService/UpdateProfile',
            profile__pb2.UpdateProfileRequest.SerializeToString,
            profile__pb2.Profile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProfileById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/models.ProfileService/GetProfileById',
            profile__pb2.GetProfileByIdRequest.SerializeToString,
            profile__pb2.Profile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProfileByUserId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/models.ProfileService/GetProfileByUserId',
            profile__pb2.GetProfileByUserIdRequest.SerializeToString,
            profile__pb2.Profile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
