# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import rolePermission_pb2 as rolePermission__pb2


class RolePermissionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRolePermission = channel.unary_unary(
                '/models.RolePermissionService/CreateRolePermission',
                request_serializer=rolePermission__pb2.CreateRolePermissionRequest.SerializeToString,
                response_deserializer=rolePermission__pb2.RolePermission.FromString,
                )
        self.GetRolePermissionsByRoleId = channel.unary_unary(
                '/models.RolePermissionService/GetRolePermissionsByRoleId',
                request_serializer=rolePermission__pb2.GetRolePermissionsByRoleIdRequest.SerializeToString,
                response_deserializer=rolePermission__pb2.RolePermissionsResponse.FromString,
                )


class RolePermissionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateRolePermission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRolePermissionsByRoleId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RolePermissionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRolePermission': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRolePermission,
                    request_deserializer=rolePermission__pb2.CreateRolePermissionRequest.FromString,
                    response_serializer=rolePermission__pb2.RolePermission.SerializeToString,
            ),
            'GetRolePermissionsByRoleId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRolePermissionsByRoleId,
                    request_deserializer=rolePermission__pb2.GetRolePermissionsByRoleIdRequest.FromString,
                    response_serializer=rolePermission__pb2.RolePermissionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'models.RolePermissionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RolePermissionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateRolePermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/models.RolePermissionService/CreateRolePermission',
            rolePermission__pb2.CreateRolePermissionRequest.SerializeToString,
            rolePermission__pb2.RolePermission.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRolePermissionsByRoleId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/models.RolePermissionService/GetRolePermissionsByRoleId',
            rolePermission__pb2.GetRolePermissionsByRoleIdRequest.SerializeToString,
            rolePermission__pb2.RolePermissionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
