# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: role.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nrole.proto\x12\x06models\" \n\x04Role\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"!\n\x11\x43reateRoleRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\x12GetRoleByIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32}\n\x0bRoleService\x12\x35\n\nCreateRole\x12\x19.models.CreateRoleRequest\x1a\x0c.models.Role\x12\x37\n\x0bGetRoleById\x12\x1a.models.GetRoleByIdRequest\x1a\x0c.models.Roleb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'role_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROLE._serialized_start=22
  _ROLE._serialized_end=54
  _CREATEROLEREQUEST._serialized_start=56
  _CREATEROLEREQUEST._serialized_end=89
  _GETROLEBYIDREQUEST._serialized_start=91
  _GETROLEBYIDREQUEST._serialized_end=123
  _ROLESERVICE._serialized_start=125
  _ROLESERVICE._serialized_end=250
# @@protoc_insertion_point(module_scope)
