# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: settings.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esettings.proto\x12\x06models\"B\n\x07Setting\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\x05\"C\n\x14\x43reateSettingRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\x05\"#\n\x15GetSettingByIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"-\n\x1aGetSettingsByUserIdRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"5\n\x10SettingsResponse\x12!\n\x08settings\x18\x01 \x03(\x0b\x32\x0f.models.Setting2\xe7\x01\n\x0eSettingService\x12>\n\rCreateSetting\x12\x1c.models.CreateSettingRequest\x1a\x0f.models.Setting\x12@\n\x0eGetSettingById\x12\x1d.models.GetSettingByIdRequest\x1a\x0f.models.Setting\x12S\n\x13GetSettingsByUserId\x12\".models.GetSettingsByUserIdRequest\x1a\x18.models.SettingsResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'settings_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SETTING._serialized_start=26
  _SETTING._serialized_end=92
  _CREATESETTINGREQUEST._serialized_start=94
  _CREATESETTINGREQUEST._serialized_end=161
  _GETSETTINGBYIDREQUEST._serialized_start=163
  _GETSETTINGBYIDREQUEST._serialized_end=198
  _GETSETTINGSBYUSERIDREQUEST._serialized_start=200
  _GETSETTINGSBYUSERIDREQUEST._serialized_end=245
  _SETTINGSRESPONSE._serialized_start=247
  _SETTINGSRESPONSE._serialized_end=300
  _SETTINGSERVICE._serialized_start=303
  _SETTINGSERVICE._serialized_end=534
# @@protoc_insertion_point(module_scope)
