# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: settings.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'settings.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esettings.proto\x12\x06models\"B\n\x07Setting\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\x05\"C\n\x14\x43reateSettingRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\x05\"#\n\x15GetSettingByIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"-\n\x1aGetSettingsByUserIdRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"5\n\x10SettingsResponse\x12!\n\x08settings\x18\x01 \x03(\x0b\x32\x0f.models.Setting2\xe7\x01\n\x0eSettingService\x12>\n\rCreateSetting\x12\x1c.models.CreateSettingRequest\x1a\x0f.models.Setting\x12@\n\x0eGetSettingById\x12\x1d.models.GetSettingByIdRequest\x1a\x0f.models.Setting\x12S\n\x13GetSettingsByUserId\x12\".models.GetSettingsByUserIdRequest\x1a\x18.models.SettingsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'settings_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETTING']._serialized_start=26
  _globals['_SETTING']._serialized_end=92
  _globals['_CREATESETTINGREQUEST']._serialized_start=94
  _globals['_CREATESETTINGREQUEST']._serialized_end=161
  _globals['_GETSETTINGBYIDREQUEST']._serialized_start=163
  _globals['_GETSETTINGBYIDREQUEST']._serialized_end=198
  _globals['_GETSETTINGSBYUSERIDREQUEST']._serialized_start=200
  _globals['_GETSETTINGSBYUSERIDREQUEST']._serialized_end=245
  _globals['_SETTINGSRESPONSE']._serialized_start=247
  _globals['_SETTINGSRESPONSE']._serialized_end=300
  _globals['_SETTINGSERVICE']._serialized_start=303
  _globals['_SETTINGSERVICE']._serialized_end=534
# @@protoc_insertion_point(module_scope)
