# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x06models\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf7\x01\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04mail\x18\x03 \x01(\t\x12\x0f\n\x07\x62locked\x18\x05 \x01(\x08\x12.\n\ncreated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07role_id\x18\x08 \x01(\x05\x12.\n\nlast_login\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x15\n\rlast_login_ip\x18\n \x01(\t\"t\n\x11\x43reateUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04mail\x18\x03 \x01(\t\x12\x0f\n\x07\x62locked\x18\x05 \x01(\x08\x12\x0f\n\x07role_id\x18\x06 \x01(\x05\x12\x15\n\rlast_login_ip\x18\x07 \x01(\t\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"*\n\x17GetUsersByRoleIdRequest\x12\x0f\n\x07role_id\x18\x01 \x01(\x05\"X\n\x1aUpdateUserLastLoginRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12.\n\nlast_login\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\",\n\rUsersResponse\x12\x1b\n\x05users\x18\x01 \x03(\x0b\x32\x0c.models.User2\x8a\x02\n\x0bUserService\x12\x35\n\nCreateUser\x12\x19.models.CreateUserRequest\x1a\x0c.models.User\x12/\n\x07GetUser\x12\x16.models.GetUserRequest\x1a\x0c.models.User\x12J\n\x10GetUsersByRoleId\x12\x1f.models.GetUsersByRoleIdRequest\x1a\x15.models.UsersResponse\x12G\n\x13UpdateUserLastLogin\x12\".models.UpdateUserLastLoginRequest\x1a\x0c.models.Userb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=56
  _globals['_USER']._serialized_end=303
  _globals['_CREATEUSERREQUEST']._serialized_start=305
  _globals['_CREATEUSERREQUEST']._serialized_end=421
  _globals['_GETUSERREQUEST']._serialized_start=423
  _globals['_GETUSERREQUEST']._serialized_end=451
  _globals['_GETUSERSBYROLEIDREQUEST']._serialized_start=453
  _globals['_GETUSERSBYROLEIDREQUEST']._serialized_end=495
  _globals['_UPDATEUSERLASTLOGINREQUEST']._serialized_start=497
  _globals['_UPDATEUSERLASTLOGINREQUEST']._serialized_end=585
  _globals['_USERSRESPONSE']._serialized_start=587
  _globals['_USERSRESPONSE']._serialized_end=631
  _globals['_USERSERVICE']._serialized_start=634
  _globals['_USERSERVICE']._serialized_end=900
# @@protoc_insertion_point(module_scope)
