# Generated by Django 3.2.16 on 2024-12-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='auth',
            name='token',
            field=models.CharField(default='juckt nicht', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auth',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
