# Generated by Django 3.2.16 on 2024-12-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0002_auto_20241229_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Codes',
        ),
    ]
