# Generated by Django 3.2.16 on 2024-12-30 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0003_auto_20241230_1505'),
    ]

    operations = [
        migrations.DeleteModel(
            name='State',
        ),
        migrations.RenameField(
            model_name='auth',
            old_name='token',
            new_name='access_token',
        ),
        migrations.AddField(
            model_name='auth',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auth',
            name='refresh_token',
            field=models.CharField(default='asd', max_length=255),
            preserve_default=False,
        ),
    ]
