# Generated by Django 3.2.16 on 2024-12-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0005_alter_auth_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
