query GetUserProfile($userId: Int!) {
  profile(userId: $userId) {
    additionalInfo
    avatarUrl
    bio
    nickname
    userId
  }
  calculateUserStats(userId: $userId) {
                totalGames
                totalWins
                totalLosses
  }
            statsByUser(userId: $userId) {
                id
                userId
                stat {
                    winnerId
                    loserId
                    createdAt
                    }
                didWin
            }
}