# Generated by Django 3.2.16 on 2024-09-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Admin'), (1, 'User')])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('secret', models.CharField(max_length=255)),
                ('is_auth', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
                ('permissions', models.ManyToManyField(to='user.Permission')),
            ],
        ),
    ]
