# Generated by Django 3.2.16 on 2024-09-12 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_auth',
            new_name='isAuth',
        ),
    ]
