# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import admin_pb2 as admin__pb2


class AdminServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAdmin = channel.unary_unary(
                '/admin.AdminService/GetAdmin',
                request_serializer=admin__pb2.GetAdminRequest.SerializeToString,
                response_deserializer=admin__pb2.Admin.FromString,
                )
        self.CreateAdmin = channel.unary_unary(
                '/admin.AdminService/CreateAdmin',
                request_serializer=admin__pb2.CreateAdminRequest.SerializeToString,
                response_deserializer=admin__pb2.Admin.FromString,
                )
        self.GetAdmins = channel.unary_unary(
                '/admin.AdminService/GetAdmins',
                request_serializer=admin__pb2.Empty.SerializeToString,
                response_deserializer=admin__pb2.AdminList.FromString,
                )


class AdminServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAdmin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAdmin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAdmins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAdmin': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAdmin,
                    request_deserializer=admin__pb2.GetAdminRequest.FromString,
                    response_serializer=admin__pb2.Admin.SerializeToString,
            ),
            'CreateAdmin': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAdmin,
                    request_deserializer=admin__pb2.CreateAdminRequest.FromString,
                    response_serializer=admin__pb2.Admin.SerializeToString,
            ),
            'GetAdmins': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAdmins,
                    request_deserializer=admin__pb2.Empty.FromString,
                    response_serializer=admin__pb2.AdminList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'admin.AdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AdminService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAdmin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/admin.AdminService/GetAdmin',
            admin__pb2.GetAdminRequest.SerializeToString,
            admin__pb2.Admin.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateAdmin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/admin.AdminService/CreateAdmin',
            admin__pb2.CreateAdminRequest.SerializeToString,
            admin__pb2.Admin.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAdmins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/admin.AdminService/GetAdmins',
            admin__pb2.Empty.SerializeToString,
            admin__pb2.AdminList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
