# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: admin.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61\x64min.proto\x12\x05\x61\x64min\"\x13\n\x05\x41\x64min\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1d\n\x0fGetAdminRequest\x12\n\n\x02id\x18\x01 \x01(\x05\" \n\x12\x43reateAdminRequest\x12\n\n\x02id\x18\x01 \x01(\x05\")\n\tAdminList\x12\x1c\n\x06\x61\x64mins\x18\x01 \x03(\x0b\x32\x0c.admin.Admin\"\x07\n\x05\x45mpty2\xa5\x01\n\x0c\x41\x64minService\x12\x30\n\x08GetAdmin\x12\x16.admin.GetAdminRequest\x1a\x0c.admin.Admin\x12\x36\n\x0b\x43reateAdmin\x12\x19.admin.CreateAdminRequest\x1a\x0c.admin.Admin\x12+\n\tGetAdmins\x12\x0c.admin.Empty\x1a\x10.admin.AdminListb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'admin_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADMIN._serialized_start=22
  _ADMIN._serialized_end=41
  _GETADMINREQUEST._serialized_start=43
  _GETADMINREQUEST._serialized_end=72
  _CREATEADMINREQUEST._serialized_start=74
  _CREATEADMINREQUEST._serialized_end=106
  _ADMINLIST._serialized_start=108
  _ADMINLIST._serialized_end=149
  _EMPTY._serialized_start=151
  _EMPTY._serialized_end=158
  _ADMINSERVICE._serialized_start=161
  _ADMINSERVICE._serialized_end=326
# @@protoc_insertion_point(module_scope)
