# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"2\n\x13\x45xchangeCodeRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\"}\n\x14\x45xchangeCodeResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x11\n\tjwt_token\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04mail\x18\x04 \x01(\t\x12\x12\n\navatar_url\x18\x05 \x01(\t\x12\x11\n\tfull_name\x18\x06 \x01(\t\"1\n\x1cGetUserIDFromJwtTokenRequest\x12\x11\n\tjwt_token\x18\x01 \x01(\t\"0\n\x1dGetUserIDFromJwtTokenResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x32\xbe\x01\n\x0b\x41uthService\x12M\n\x14\x45xchangeCodeForToken\x12\x19.auth.ExchangeCodeRequest\x1a\x1a.auth.ExchangeCodeResponse\x12`\n\x15GetUserIDFromJwtToken\x12\".auth.GetUserIDFromJwtTokenRequest\x1a#.auth.GetUserIDFromJwtTokenResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXCHANGECODEREQUEST._serialized_start=20
  _EXCHANGECODEREQUEST._serialized_end=70
  _EXCHANGECODERESPONSE._serialized_start=72
  _EXCHANGECODERESPONSE._serialized_end=197
  _GETUSERIDFROMJWTTOKENREQUEST._serialized_start=199
  _GETUSERIDFROMJWTTOKENREQUEST._serialized_end=248
  _GETUSERIDFROMJWTTOKENRESPONSE._serialized_start=250
  _GETUSERIDFROMJWTTOKENRESPONSE._serialized_end=298
  _AUTHSERVICE._serialized_start=301
  _AUTHSERVICE._serialized_end=491
# @@protoc_insertion_point(module_scope)
