# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"\x12\n\x04\x41uth\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1c\n\x0eGetAuthRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1f\n\x11\x43reateAuthRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"%\n\x08\x41uthList\x12\x19\n\x05\x61uths\x18\x01 \x03(\x0b\x32\n.auth.Auth\"\x07\n\x05\x45mpty2\x96\x01\n\x0b\x41uthService\x12+\n\x07GetAuth\x12\x14.auth.GetAuthRequest\x1a\n.auth.Auth\x12\x31\n\nCreateAuth\x12\x17.auth.CreateAuthRequest\x1a\n.auth.Auth\x12\'\n\x08GetAuths\x12\x0b.auth.Empty\x1a\x0e.auth.AuthListb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUTH._serialized_start=20
  _AUTH._serialized_end=38
  _GETAUTHREQUEST._serialized_start=40
  _GETAUTHREQUEST._serialized_end=68
  _CREATEAUTHREQUEST._serialized_start=70
  _CREATEAUTHREQUEST._serialized_end=101
  _AUTHLIST._serialized_start=103
  _AUTHLIST._serialized_end=140
  _EMPTY._serialized_start=142
  _EMPTY._serialized_end=149
  _AUTHSERVICE._serialized_start=152
  _AUTHSERVICE._serialized_end=302
# @@protoc_insertion_point(module_scope)
