# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import auth_pb2 as auth__pb2


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAuth = channel.unary_unary(
                '/auth.AuthService/GetAuth',
                request_serializer=auth__pb2.GetAuthRequest.SerializeToString,
                response_deserializer=auth__pb2.Auth.FromString,
                )
        self.CreateAuth = channel.unary_unary(
                '/auth.AuthService/CreateAuth',
                request_serializer=auth__pb2.CreateAuthRequest.SerializeToString,
                response_deserializer=auth__pb2.Auth.FromString,
                )
        self.GetAuths = channel.unary_unary(
                '/auth.AuthService/GetAuths',
                request_serializer=auth__pb2.Empty.SerializeToString,
                response_deserializer=auth__pb2.AuthList.FromString,
                )


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAuth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAuth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuths(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAuth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuth,
                    request_deserializer=auth__pb2.GetAuthRequest.FromString,
                    response_serializer=auth__pb2.Auth.SerializeToString,
            ),
            'CreateAuth': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAuth,
                    request_deserializer=auth__pb2.CreateAuthRequest.FromString,
                    response_serializer=auth__pb2.Auth.SerializeToString,
            ),
            'GetAuths': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuths,
                    request_deserializer=auth__pb2.Empty.FromString,
                    response_serializer=auth__pb2.AuthList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAuth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.AuthService/GetAuth',
            auth__pb2.GetAuthRequest.SerializeToString,
            auth__pb2.Auth.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateAuth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.AuthService/CreateAuth',
            auth__pb2.CreateAuthRequest.SerializeToString,
            auth__pb2.Auth.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAuths(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.AuthService/GetAuths',
            auth__pb2.Empty.SerializeToString,
            auth__pb2.AuthList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
