# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import chat_pb2 as chat__pb2


class ChatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateChatRoom = channel.unary_unary(
                '/chat.ChatService/CreateChatRoom',
                request_serializer=chat__pb2.CreateChatRoomRequest.SerializeToString,
                response_deserializer=chat__pb2.ChatRoom.FromString,
                )
        self.GetChatRoomById = channel.unary_unary(
                '/chat.ChatService/GetChatRoomById',
                request_serializer=chat__pb2.GetChatRoomRequest.SerializeToString,
                response_deserializer=chat__pb2.ChatRoom.FromString,
                )
        self.ListChatRooms = channel.unary_stream(
                '/chat.ChatService/ListChatRooms',
                request_serializer=chat__pb2.Empty.SerializeToString,
                response_deserializer=chat__pb2.ChatRoom.FromString,
                )


class ChatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateChatRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChatRoomById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChatRooms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateChatRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateChatRoom,
                    request_deserializer=chat__pb2.CreateChatRoomRequest.FromString,
                    response_serializer=chat__pb2.ChatRoom.SerializeToString,
            ),
            'GetChatRoomById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChatRoomById,
                    request_deserializer=chat__pb2.GetChatRoomRequest.FromString,
                    response_serializer=chat__pb2.ChatRoom.SerializeToString,
            ),
            'ListChatRooms': grpc.unary_stream_rpc_method_handler(
                    servicer.ListChatRooms,
                    request_deserializer=chat__pb2.Empty.FromString,
                    response_serializer=chat__pb2.ChatRoom.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateChatRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chat.ChatService/CreateChatRoom',
            chat__pb2.CreateChatRoomRequest.SerializeToString,
            chat__pb2.ChatRoom.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetChatRoomById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chat.ChatService/GetChatRoomById',
            chat__pb2.GetChatRoomRequest.SerializeToString,
            chat__pb2.ChatRoom.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListChatRooms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/chat.ChatService/ListChatRooms',
            chat__pb2.Empty.SerializeToString,
            chat__pb2.ChatRoom.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
