# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gameEvent.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgameEvent.proto\x12\rtranscendence\x1a\x1fgoogle/protobuf/timestamp.proto\"\x7f\n\tGameEvent\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07game_id\x18\x02 \x01(\x05\x12\x12\n\nevent_type\x18\x03 \x01(\t\x12\x12\n\nevent_data\x18\x04 \x01(\t\x12-\n\ttimestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\",\n\x13GetGameEventRequest\x12\x15\n\rgame_event_id\x18\x01 \x01(\x05\"\x80\x01\n\x16\x43reateGameEventRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\x05\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x12\n\nevent_data\x18\x03 \x01(\t\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\xb4\x01\n\x10GameEventService\x12L\n\x0cGetGameEvent\x12\".transcendence.GetGameEventRequest\x1a\x18.transcendence.GameEvent\x12R\n\x0f\x43reateGameEvent\x12%.transcendence.CreateGameEventRequest\x1a\x18.transcendence.GameEventb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gameEvent_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GAMEEVENT._serialized_start=67
  _GAMEEVENT._serialized_end=194
  _GETGAMEEVENTREQUEST._serialized_start=196
  _GETGAMEEVENTREQUEST._serialized_end=240
  _CREATEGAMEEVENTREQUEST._serialized_start=243
  _CREATEGAMEEVENTREQUEST._serialized_end=371
  _GAMEEVENTSERVICE._serialized_start=374
  _GAMEEVENTSERVICE._serialized_end=554
# @@protoc_insertion_point(module_scope)
