# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import profile_pb2 as profile__pb2


class ProfileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateProfile = channel.unary_unary(
                '/models.ProfileService/CreateProfile',
                request_serializer=profile__pb2.CreateProfileRequest.SerializeToString,
                response_deserializer=profile__pb2.Profile.FromString,
                )
        self.UpdateProfile = channel.unary_unary(
                '/models.ProfileService/UpdateProfile',
                request_serializer=profile__pb2.UpdateProfileRequest.SerializeToString,
                response_deserializer=profile__pb2.Profile.FromString,
                )
        self.GetProfileById = channel.unary_unary(
                '/models.ProfileService/GetProfileById',
                request_serializer=profile__pb2.GetProfileByIdRequest.SerializeToString,
                response_deserializer=profile__pb2.Profile.FromString,
                )
        self.GetProfileByUserId = channel.unary_unary(
                '/models.ProfileService/GetProfileByUserId',
                request_serializer=profile__pb2.GetProfileByUserIdRequest.SerializeToString,
                response_deserializer=profile__pb2.Profile.FromString,
                )


class ProfileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfileById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfileByUserId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProfile,
                    request_deserializer=profile__pb2.CreateProfileRequest.FromString,
                    response_serializer=profile__pb2.Profile.SerializeToString,
            ),
            'UpdateProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProfile,
                    request_deserializer=profile__pb2.UpdateProfileRequest.FromString,
                    response_serializer=profile__pb2.Profile.SerializeToString,
            ),
            'GetProfileById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfileById,
                    request_deserializer=profile__pb2.GetProfileByIdRequest.FromString,
                    response_serializer=profile__pb2.Profile.SerializeToString,
            ),
            'GetProfileByUserId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfileByUserId,
                    request_deserializer=profile__pb2.GetProfileByUserIdRequest.FromString,
                    response_serializer=profile__pb2.Profile.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'models.ProfileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProfileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/models.ProfileService/CreateProfile',
            profile__pb2.CreateProfileRequest.SerializeToString,
            profile__pb2.Profile.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/models.ProfileService/UpdateProfile',
            profile__pb2.UpdateProfileRequest.SerializeToString,
            profile__pb2.Profile.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProfileById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/models.ProfileService/GetProfileById',
            profile__pb2.GetProfileByIdRequest.SerializeToString,
            profile__pb2.Profile.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProfileByUserId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/models.ProfileService/GetProfileByUserId',
            profile__pb2.GetProfileByUserIdRequest.SerializeToString,
            profile__pb2.Profile.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
