# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import role_pb2 as role__pb2


class RoleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRole = channel.unary_unary(
                '/models.RoleService/CreateRole',
                request_serializer=role__pb2.CreateRoleRequest.SerializeToString,
                response_deserializer=role__pb2.Role.FromString,
                )
        self.GetRoleById = channel.unary_unary(
                '/models.RoleService/GetRoleById',
                request_serializer=role__pb2.GetRoleByIdRequest.SerializeToString,
                response_deserializer=role__pb2.Role.FromString,
                )


class RoleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoleById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRole': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRole,
                    request_deserializer=role__pb2.CreateRoleRequest.FromString,
                    response_serializer=role__pb2.Role.SerializeToString,
            ),
            'GetRoleById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoleById,
                    request_deserializer=role__pb2.GetRoleByIdRequest.FromString,
                    response_serializer=role__pb2.Role.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'models.RoleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RoleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/models.RoleService/CreateRole',
            role__pb2.CreateRoleRequest.SerializeToString,
            role__pb2.Role.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRoleById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/models.RoleService/GetRoleById',
            role__pb2.GetRoleByIdRequest.SerializeToString,
            role__pb2.Role.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
