# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rolePermission.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14rolePermission.proto\x12\x06models\"8\n\x0eRolePermission\x12\x0f\n\x07role_id\x18\x01 \x01(\x05\x12\x15\n\rpermission_id\x18\x02 \x01(\x05\"E\n\x1b\x43reateRolePermissionRequest\x12\x0f\n\x07role_id\x18\x01 \x01(\x05\x12\x15\n\rpermission_id\x18\x02 \x01(\x05\"4\n!GetRolePermissionsByRoleIdRequest\x12\x0f\n\x07role_id\x18\x01 \x01(\x05\"J\n\x17RolePermissionsResponse\x12/\n\x0frolePermissions\x18\x01 \x03(\x0b\x32\x16.models.RolePermission2\xd6\x01\n\x15RolePermissionService\x12S\n\x14\x43reateRolePermission\x12#.models.CreateRolePermissionRequest\x1a\x16.models.RolePermission\x12h\n\x1aGetRolePermissionsByRoleId\x12).models.GetRolePermissionsByRoleIdRequest\x1a\x1f.models.RolePermissionsResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rolePermission_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROLEPERMISSION._serialized_start=32
  _ROLEPERMISSION._serialized_end=88
  _CREATEROLEPERMISSIONREQUEST._serialized_start=90
  _CREATEROLEPERMISSIONREQUEST._serialized_end=159
  _GETROLEPERMISSIONSBYROLEIDREQUEST._serialized_start=161
  _GETROLEPERMISSIONSBYROLEIDREQUEST._serialized_end=213
  _ROLEPERMISSIONSRESPONSE._serialized_start=215
  _ROLEPERMISSIONSRESPONSE._serialized_end=289
  _ROLEPERMISSIONSERVICE._serialized_start=292
  _ROLEPERMISSIONSERVICE._serialized_end=506
# @@protoc_insertion_point(module_scope)
