# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import stat_pb2 as stat__pb2


class StatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStats = channel.unary_unary(
                '/stat.StatService/GetStats',
                request_serializer=stat__pb2.Empty.SerializeToString,
                response_deserializer=stat__pb2.StatList.FromString,
                )
        self.GetStat = channel.unary_unary(
                '/stat.StatService/GetStat',
                request_serializer=stat__pb2.GetStatRequest.SerializeToString,
                response_deserializer=stat__pb2.Stat.FromString,
                )
        self.CreateStat = channel.unary_unary(
                '/stat.StatService/CreateStat',
                request_serializer=stat__pb2.CreateStatRequest.SerializeToString,
                response_deserializer=stat__pb2.Stat.FromString,
                )


class StatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateStat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=stat__pb2.Empty.FromString,
                    response_serializer=stat__pb2.StatList.SerializeToString,
            ),
            'GetStat': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStat,
                    request_deserializer=stat__pb2.GetStatRequest.FromString,
                    response_serializer=stat__pb2.Stat.SerializeToString,
            ),
            'CreateStat': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateStat,
                    request_deserializer=stat__pb2.CreateStatRequest.FromString,
                    response_serializer=stat__pb2.Stat.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stat.StatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stat.StatService/GetStats',
            stat__pb2.Empty.SerializeToString,
            stat__pb2.StatList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stat.StatService/GetStat',
            stat__pb2.GetStatRequest.SerializeToString,
            stat__pb2.Stat.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateStat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stat.StatService/CreateStat',
            stat__pb2.CreateStatRequest.SerializeToString,
            stat__pb2.Stat.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
