# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"x\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06secret\x18\x03 \x01(\t\x12%\n\x0bpermissions\x18\x04 \x03(\x0b\x32\x10.user.Permission\x12\x0e\n\x06isAuth\x18\x05 \x01(\x08\x12\x0f\n\x07\x62locked\x18\x06 \x01(\x08\"%\n\x08UserList\x12\x19\n\x05users\x18\x01 \x03(\x0b\x32\n.user.User\"\x07\n\x05\x45mpty\"<\n\nPermission\x12\n\n\x02id\x18\x01 \x01(\x05\x12\"\n\x04type\x18\x02 \x01(\x0e\x32\x14.user.PermissionType\"y\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06secret\x18\x02 \x01(\t\x12%\n\x0bpermissions\x18\x03 \x03(\x0b\x32\x10.user.Permission\x12\x0e\n\x06isAuth\x18\x04 \x01(\x08\x12\x0f\n\x07\x62locked\x18\x05 \x01(\x08\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05*%\n\x0ePermissionType\x12\t\n\x05\x41\x44MIN\x10\x00\x12\x08\n\x04USER\x10\x01\x32\x96\x01\n\x0bUserService\x12\'\n\x08GetUsers\x12\x0b.user.Empty\x1a\x0e.user.UserList\x12+\n\x07GetUser\x12\x14.user.GetUserRequest\x1a\n.user.User\x12\x31\n\nCreateUser\x12\x17.user.CreateUserRequest\x1a\n.user.Userb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PERMISSIONTYPE']._serialized_start=405
  _globals['_PERMISSIONTYPE']._serialized_end=442
  _globals['_USER']._serialized_start=20
  _globals['_USER']._serialized_end=140
  _globals['_USERLIST']._serialized_start=142
  _globals['_USERLIST']._serialized_end=179
  _globals['_EMPTY']._serialized_start=181
  _globals['_EMPTY']._serialized_end=188
  _globals['_PERMISSION']._serialized_start=190
  _globals['_PERMISSION']._serialized_end=250
  _globals['_CREATEUSERREQUEST']._serialized_start=252
  _globals['_CREATEUSERREQUEST']._serialized_end=373
  _globals['_GETUSERREQUEST']._serialized_start=375
  _globals['_GETUSERREQUEST']._serialized_end=403
  _globals['_USERSERVICE']._serialized_start=445
  _globals['_USERSERVICE']._serialized_end=595
# @@protoc_insertion_point(module_scope)
