# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userAchievement.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15userAchievement.proto\x12\x06models\x1a\x1fgoogle/protobuf/timestamp.proto\"w\n\x0fUserAchievement\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x16\n\x0e\x61\x63hievement_id\x18\x03 \x01(\x05\x12/\n\x0bunlocked_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"+\n\x1dGetUserAchievementByIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"5\n\"GetUserAchievementsByUserIdRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"x\n\x1c\x43reateUserAchievementRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x16\n\x0e\x61\x63hievement_id\x18\x02 \x01(\x05\x12/\n\x0bunlocked_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"M\n\x18UserAchievementsResponse\x12\x31\n\x10userAchievements\x18\x01 \x03(\x0b\x32\x17.models.UserAchievement2\xb7\x02\n\x16UserAchievementService\x12X\n\x16GetUserAchievementById\x12%.models.GetUserAchievementByIdRequest\x1a\x17.models.UserAchievement\x12k\n\x1bGetUserAchievementsByUserId\x12*.models.GetUserAchievementsByUserIdRequest\x1a .models.UserAchievementsResponse\x12V\n\x15\x43reateUserAchievement\x12$.models.CreateUserAchievementRequest\x1a\x17.models.UserAchievementb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'userAchievement_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERACHIEVEMENT._serialized_start=66
  _USERACHIEVEMENT._serialized_end=185
  _GETUSERACHIEVEMENTBYIDREQUEST._serialized_start=187
  _GETUSERACHIEVEMENTBYIDREQUEST._serialized_end=230
  _GETUSERACHIEVEMENTSBYUSERIDREQUEST._serialized_start=232
  _GETUSERACHIEVEMENTSBYUSERIDREQUEST._serialized_end=285
  _CREATEUSERACHIEVEMENTREQUEST._serialized_start=287
  _CREATEUSERACHIEVEMENTREQUEST._serialized_end=407
  _USERACHIEVEMENTSRESPONSE._serialized_start=409
  _USERACHIEVEMENTSRESPONSE._serialized_end=486
  _USERACHIEVEMENTSERVICE._serialized_start=489
  _USERACHIEVEMENTSERVICE._serialized_end=800
# @@protoc_insertion_point(module_scope)
