# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\x1a\x1fgoogle/protobuf/timestamp.proto\"e\n\x08\x43hatRoom\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12.\n\ncreated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07game_id\x18\x04 \x01(\x05\" \n\x12GetChatRoomRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"6\n\x15\x43reateChatRoomRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07game_id\x18\x02 \x01(\x05\".\n\x1bGetChatRoomsByUserIdRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"#\n\x15\x44\x65leteChatRoomRequest\x12\n\n\x02id\x18\x01 \x01(\x05\";\n\x15ListChatRoomsResponse\x12\"\n\nchat_rooms\x18\x01 \x03(\x0b\x32\x0e.chat.ChatRoom\"\x07\n\x05\x45mpty2\xdc\x02\n\x0f\x43hatRoomService\x12;\n\x0fGetChatRoomById\x12\x18.chat.GetChatRoomRequest\x1a\x0e.chat.ChatRoom\x12\x39\n\rListChatRooms\x12\x0b.chat.Empty\x1a\x1b.chat.ListChatRoomsResponse\x12=\n\x0e\x43reateChatRoom\x12\x1b.chat.CreateChatRoomRequest\x1a\x0e.chat.ChatRoom\x12:\n\x0e\x44\x65leteChatRoom\x12\x1b.chat.DeleteChatRoomRequest\x1a\x0b.chat.Empty\x12V\n\x14GetChatRoomsByUserId\x12!.chat.GetChatRoomsByUserIdRequest\x1a\x1b.chat.ListChatRoomsResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHATROOM._serialized_start=53
  _CHATROOM._serialized_end=154
  _GETCHATROOMREQUEST._serialized_start=156
  _GETCHATROOMREQUEST._serialized_end=188
  _CREATECHATROOMREQUEST._serialized_start=190
  _CREATECHATROOMREQUEST._serialized_end=244
  _GETCHATROOMSBYUSERIDREQUEST._serialized_start=246
  _GETCHATROOMSBYUSERIDREQUEST._serialized_end=292
  _DELETECHATROOMREQUEST._serialized_start=294
  _DELETECHATROOMREQUEST._serialized_end=329
  _LISTCHATROOMSRESPONSE._serialized_start=331
  _LISTCHATROOMSRESPONSE._serialized_end=390
  _EMPTY._serialized_start=392
  _EMPTY._serialized_end=399
  _CHATROOMSERVICE._serialized_start=402
  _CHATROOMSERVICE._serialized_end=750
# @@protoc_insertion_point(module_scope)
